[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[functions]
  directory = "functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
